version: "3"
services:
  database:
    image: "postgres:13" # use official postgres version 13
    networks:
      - my-network
    env_file:
      - ./order-service/database.env # configure postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    ports:
      - "5432:5432"
  
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    restart: always
    mem_limit: 350m
    networks:
      - my-network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    mem_limit: 350m
    networks:
      - my-network
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

volumes:
  postgres-data:  # named volumes can be managed easier using docker-compose
    driver: local

networks:
  my-network:
    name: my-network
