version: "3"
services:
  database:
    image: "postgres:13" # use official postgres version 13
    env_file:
      - ./order-service/database.env # configure postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    ports:
      - "5432:5432"

volumes:
  postgres-data:  # named volumes can be managed easier using docker-compose
    driver: local
