# global:
#   scrape_interval: 10s
#   scrape_timeout: 10s

# rule_files:
#   - alert.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'order-service'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8080']
  - job_name: 'grafana'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']